name: "Build CUDA libs for jaxmg"
description: "Build the CUDA shared libraries and place them in src/jaxmg/bin"
runs:
  using: "composite"
  steps:
    - name: Install CUDA toolkit and deps
      shell: bash
      run: |
        set -ex
        yum install -y --nogpgcheck wget git cmake3 gcc-toolset-11 gcc-toolset-11-gcc-c++ yum-utils

        # Enable GCC 11
        source /opt/rh/gcc-toolset-11/enable

        # Install CUDA repo & toolkit (adjust versions to match your current script)
        yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
        yum clean all
        yum -y --nogpgcheck install cuda-toolkit-12-8

        # Optional: cuDNN or others
        yum -y --nogpgcheck install libcudnn9-cuda-12 libcudnn9-devel-cuda-12 || echo "cuDNN not available, skipping"

        # Symlink CUDA root, if needed
        ln -sf /usr/local/cuda-12.6 /usr/local/cuda || true

        # JAXlib looks for CUPTI headers in extras/CUPTI/include/
        # Create symlink from extras/CUPTI/include to main include directory
        mkdir -p /usr/local/cuda/extras/CUPTI
        ln -sfn /usr/local/cuda/include /usr/local/cuda/extras/CUPTI/include
        ls -la /usr/local/cuda/extras/CUPTI/include/cupti*.h

    - name: Build CUDA libs via CMake
      shell: bash
      run: |
        set -ex
        source /opt/rh/gcc-toolset-11/enable

        export CUDA_ROOT=/usr/local/cuda
        export CUDNN_ROOT=/usr
        export PATH=/usr/local/cuda/bin:$PATH
        export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

        mkdir -p third_party/gpus
        ln -sfn /usr/local/cuda third_party/gpus/cuda

        mkdir -p build
        cd build
        cmake3 -DCMAKE_BUILD_TYPE=Release ..
        cmake3 --build . --target install -- -j"$(nproc)"
        cd ..

        echo "Built libs:"
        ls -la src/jaxmg/bin/
