pipeline {
    agent {
        dockerfile {
            filename '.jenkins/Dockerfile'
            args '--gpus 2'
            label 'docker && v100'
        }
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
    }
    environment {
        HOME = "$WORKSPACE"
    }
    stages {
        stage('Build') {
            environment {
                PARALLEL = "${env.PARALLEL}"
            }
            steps {
                sh '''#!/bin/bash -ex
                    export CUDA_ROOT=/usr/local/cuda
                    export CUDNN_ROOT=/usr
                    export PATH=/usr/local/cuda/bin:$PATH
                    export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
                    mkdir -p third_party/gpus
                    ln -sfn third_party/gpus/cuda
                    mkdir -p build && cd build
                    cmake -DCMAKE_BUILD_TYPE=Release ..
                    cmake --build . --target install -- -j${PARALLEL}
                '''
                sh '''#!/bin/bash -ex
                    python3 -m venv $HOME/.venv
                    source $HOME/.venv/bin/activate
                    python3 -m pip install --upgrade pip build
                    python3 -m build --wheel
                    python3 -m pip install dist/jaxmg-*.whl
                    # TODO python versions
                '''
            }
        }
        stage('Test') {
            environment {
                CUDA_VISIBLE_DEVICES = 2
            }
            steps {
                sh '''#!/bin/bash -ex
                    source $HOME/.venv/bin/activate
                    python3 -m pip install 'pytest==8.2.1'
                    python3 -m pytest
                '''
            }
        }
    }
}
